### ISSUE TITLE
Anisotropic Analysis

### ISSUE THREAD

**Issue by moses-musau** [fleurhierink/Population_Access#1]
Hi.

I understand that based on the paper, isotropic analysis was desired. 

Could you provide the syntax for including the DEM aspect in the model? That is, to perform anisotropic analysis.

Also, given that R has a costDistance() function, why was it necessary to perform the cost distance algorithm in python?

**Comment by fleurhierink** [comment]
Thanks a lot for your question! Unfortunately, I do not have a script ready to perform the accessibility analysis with the DEM. But it would require you to incorporate an algorithm that accounts for the direction of movement on slopes. Such as the Toblers hiking equation for example. I'm most familiar with applying this correction in the AccessMod software, an open source WHO tool that facilitates modelling accessibility.

The costDistance() function from the gdistance library in R is a very effective library. However, the calculation of the transition matrix or the computation of the graph requires a lot of RAM and memory. Especially for large countries, such as Angola or the Democratic Republic of Congo this was a very RAM inefficient proccess, even in a high performing compution (HPC) environment. The Arcpy commands required way less memory and performed much better, even on a normal desktop. 

Please let me know if you require any additional information!

**Comment by moses-musau** [comment]
Thanks for the fast reply.

Yes, I am aware of AccessMod and the Toblers hiking equation. Although I find Accessmod quite "cumbersome" especially when I need to perform multiple analysis. I was hoping to switch to R as I can loop/apply across different inputs. I will fidn my way around and hopefully share the output.

I get the argument for python regarding efficiency. I am not "that good" in python and the documentation in the .py file is limited. Do you mind sharing the same implementation in R?

**Comment by fleurhierink** [comment]
I'm looking forward to seeing your results! Unfortunately, we stopped the development of the code in R, because in this case Python outperformed R in terms of computation efficiency. I listed the main functions you would need to perform a similar analysis in R:

> **create a transition matrix**
> transition_matrix <- gdistance::transition(friction, function(x) 1/mean(x), 8) 
> transition_geocorrect <- gdistance::geoCorrection(transition_matrix) 
> 
> **perform accessibility analysis, points represents your facility layer with geocoordinates**
> access <- gdistance::accCost(transition_geocorrect, points)

I hope this is helpful!
